### ISSUE TITLE
nodemon not found, 

### ISSUE THREAD

**Issue by gbishop** [osenvosem/react-mobx-boilerplate#1]
Total newb here trying to get started with your boilerplate. I have cloned, initialized, and then when I run `npm start` I get:

```
react-mobx-boilerplate (master)$ npm start

> one@1.0.0 start /home/gb/tmp/react-mobx-boilerplate
> NODE_ENV=development nodemon server/index.js -w server/

sh: 1: nodemon: not found
```

So, I install nodemon with `npm install nodemon --save` and then I get:

```
react-mobx-boilerplate (master *)$ npm start

> one@1.0.0 start /home/gb/tmp/react-mobx-boilerplate
> NODE_ENV=development nodemon server/index.js -w server/

[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/gb/tmp/react-mobx-boilerplate/server/**/*
[nodemon] starting `node server/index.js`
/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^
ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "base" at 0, attempted to resolve relative to "/home/gb/tmp/react-mobx-boilerplate/server"
    at /home/gb/tmp/react-mobx-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204:17
    at Array.map (native)
    at Function.normalisePlugins (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.init (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:488:10)
    at compile (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-register/lib/node.js:112:69)
    at loader (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-register/lib/node.js:158:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

I bet I'm missing something simple.

**Comment by osenvosem** [comment]
@gbishop sorry, it is my fault. Forgot to add a couple of dev dependencies. Try it again please.

**Comment by gbishop** [comment]
I'm still getting that second error

```
react-mobx-boilerplate (master)$ npm start

> one@1.0.0 start /home/gb/tmp/react-mobx-boilerplate
> NODE_ENV=development nodemon server/index.js -w server/

[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/gb/tmp/react-mobx-boilerplate/server/**/*
[nodemon] starting `node server/index.js`
/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "base" at 0, attempted to resolve relative to "/home/gb/tmp/react-mobx-boilerplate/server"
    at /home/gb/tmp/react-mobx-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204:17
    at Array.map (native)
    at Function.normalisePlugins (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.init (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:488:10)
    at compile (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-register/lib/node.js:112:69)
    at loader (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-register/lib/node.js:158:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/gb/tmp/react-mobx-boilerplate/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

**Comment by osenvosem** [comment]
@gbishop ok, try it again please.

**Comment by gbishop** [comment]
Working now. Thanks!

**Comment by osenvosem** [comment]
@gbishop you are welcome. =)
